### ISSUE TITLE
[NFR] add option for disable and enable foreigh key

### ISSUE THREAD

**Issue by olegatro** [phalcon/migrations#11]
When we migrating some tables, we don't control order of this tables.
And if we have foreign keys of that tables, we have errors.

So we should have some mechanic to disable and enable foreign key checks. 

```sql
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE ...

SET FOREIGN_KEY_CHECKS=1;
```

**Comment by Jeckerson** [comment]
Related #6

**Comment by Jeckerson** [comment]
Related #20

**Comment by Jeckerson** [comment]
@olegatro Could you provide some examples by updating your original post?

**Comment by olegatro** [comment]
Updated
