### ISSUE TITLE
generating migration for Postgres does not create indexes

### ISSUE THREAD

**Issue by MaksymLevenets** [phalcon/migrations#118]
https://github.com/phalcon/migrations/blob/fec5c239a9abf718778e577cdd9eceb880ea624e/src/Migration/Action/Generate.php#L280

This part always skip index column if postgres  adapter used.

**Comment by BeMySlaveDarlin** [comment]
Fixed in PR #120

**Comment by Jeckerson** [comment]
Fixed in https://github.com/phalcon/migrations/releases/tag/v2.2.1
