### ISSUE TITLE
Migration run wouldn't create mysql view

### ISSUE THREAD

**Issue by scrptd95** [phalcon/migrations#129]
### Expected and Actual Behavior

Hi Guys, recently i created a view in my mysql db and was curious if the phalcon/migrations util would pick it up. 
I ran `phalcon migrations generate` to generate the migration file, wiped my tables and executed `phalcon migrations run` to check whether my db will be correctly created or not.

Migration File:
`<?php

use Phalcon\Db\Column;
use Phalcon\Db\Exception;
use Phalcon\Db\Index;
use Phalcon\Db\Reference;
use Phalcon\Migrations\Mvc\Model\Migration;

/**
 * Class ViolationsMigration_104
 */
class ViolationsMigration_104 extends Migration
{
    /**
     * Define the table structure
     *
     * @return void
     * @throws Exception
     */
    public function morph(): void
    {
        $this->morphTable('violations', [
            'columns' => [
                new Column(
                    'violations',
                    [
                        'type' => Column::TYPE_DECIMAL,
                        'notNull' => false,
                        'size' => 32,
                        'first' => true
                    ]
                ),
                new Column(
                    'logged_for',
                    [
                        'type' => Column::TYPE_INTEGER,
                        'notNull' => true,
                        'size' => 1,
                        'after' => 'violations'
                    ]
                ),
            ],
            'options' => [
                'TABLE_TYPE' => 'VIEW',
                'AUTO_INCREMENT' => '',
                'ENGINE' => '',
                'TABLE_COLLATION' => '',
            ],
        ]);
    }

    /**
     * Run the migrations
     *
     * @return void
     */
    public function up(): void
    {
    }

    /**
     * Reverse the migrations
     *
     * @return void
     */
    public function down(): void
    {
    }
}`

Create table syntax of created table via migration run:
`CREATE TABLE `violations` (
  `violations` decimal(32,0) DEFAULT NULL,
  `logged_for` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;`

The table gets created but not as a view. It seems that the `TABLE_TYPE` gets ignored ? Also i'm curious where or if the migration generate task stores/saves the query related to the view.

### Expected behavior:

- `phalcon migrations generate` correctly creates the migration file for mysql view
- `phalcon migrations run`correctly creates the view in the db

### Details

* Phalcon Framework version: 4.1.2
* PHP Version: 7.4.27
* Operating System: Linux Ubuntu 20.04
* Server: Nginx 
* DB: mysql

**Comment by Jeckerson** [comment]
Hello, this is new feature. At that moment there is no logic to auto detect `SQL View` and create it via `morph()` method.

What you can do now, is to create empty migration and put SQL code of view creation inside `up()` method, example:
```php
public function up()
{
   $this->getConnection()->execute('CREATE VIEW ...');
}
```

**Comment by scrptd95** [comment]
Ah thx for the hint.
For now i'll handle it this way.

Also thank you for your fast response!

**Comment by secgin** [comment]
Hi, How can I manage the migrate order? Views should run last.
