### ISSUE TITLE
Integrate Phalcon cli-options-parser

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/migrations#20]
Instead current old implementation, use common one:
* https://github.com/phalcon/cli-options-parser

**Comment by ruudboon** [comment]
Maybe we can also evaluate the need for adding the word `migrations` when implementing this.
Current situation:
```
vendor/bin/phalcon-migrations migration run
vendor/bin/phalcon-migrations migration generate
```
Proposal
```
vendor/bin/phalcon-migrations run
vendor/bin/phalcon-migrations generate
```
