### ISSUE TITLE
Run migration for fields type of date and datetime

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/migrations#22]
If I have field name "create_date" of type "datetime" (or "date") and when I run command:
vendor/bin/phalcon migration run --verbose
I see that:
1576145901.8674: ALTER TABLE `test` MODIFY `create_date` DATE NOT NULL AFTER `name`  => 1576145901.89 (0.022550106048584)
regardless of whether something has been changed or not

Finally if the table has a lot of records, execution time of SQL queries it is very long.

My database: MySQL 5.5
PHP version: 7.2
Phalcon version: 3.4.1
Phalcon phalcon-devtools version: 3.4.9

**Comment by Jeckerson** [comment]
Fixed in [3.4.10](https://github.com/phalcon/phalcon-devtools/releases/tag/v3.4.10)
