### ISSUE TITLE
Class Phalcon\Db\Column  no constant defined for datatype "Time"

### ISSUE THREAD

**Issue by monkeyhead89** [phalcon/migrations#8]
Hi,

When creating a new column it appears that there is no option to use the `TIME` datatype. 
i.e

``` php
new Column('Time', [
    'type'    => Column::TYPE_TIME,
    'size'    => 10,
    'notNull' => true,
]);
```

I suspect that this is down to a constant not being defined for it.

**Comment by Jeckerson** [comment]
Fixed
