### ISSUE TITLE
Decimal and Float Column size is not saving

### ISSUE THREAD

**Issue by jdubreville** [phalcon/migrations#92]
When generating a migration the size of a decimal and float column is not being saved as it was in previous versions.  This prevents the migration from being pushed forward and you will get an error that Float(M,D) or Decimal(M,D) and that M must always be >= D.

**Comment by jdubreville** [comment]
So I dug in a little more and Float and Decimal are in the noSizeTypes list which I don't think this is correct for MySql as the size is the precision of the number being stored.  I don't mind making a pull request for this but it would need to update back to 1.2 and up.

**Comment by Jeckerson** [comment]
@jdubreville Could you make an PR please?
